**Step 1: Import packages and classes**

In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression

Variables
      
      1.Independent
      2.Dependent

In [5]:
x = np.array([25, 35, 45, 55, 65, 75])
y = np.array([5, 20, 14, 32, 22, 38])

In [6]:
print(x)
print(y)

[25 35 45 55 65 75]
[ 5 20 14 32 22 38]


1.The input x and output y.

2.reshape() on x because this array is required to be two dimensional, or to be more precise, to have one column and as many rows as necessary

In [8]:
x=x.reshape((-1, 1))

In [9]:
print(x)
x.shape

[[25]
 [35]
 [45]
 [55]
 [65]
 [75]]


(6, 1)

**Create a model and fit it**

In [16]:
model = LinearRegression()

In [17]:
model.fit(x, y)

LinearRegression()

Once you have your model titled , you can get the results to checkk whther the model works satisfactory and interpret it.

In [20]:
r_sq_score = model.score(x, y)
print('cofficient of determination:', r_sq_score)

cofficient of determination: 0.7158756137479542


In [22]:
print('intercept:', model.intercept_)

intercept: -5.166666666666668


In [23]:
print('slope:', model.coef_)

slope: [0.54]


In [24]:
y_pred = model.predict(x)

In [25]:
print("actual values",y)
print('predicted response:', y_pred)

actual values [ 5 20 14 32 22 38]
predicted response: [ 8.33333333 13.73333333 19.13333333 24.53333333 29.93333333 35.33333333]
